### ISSUE TITLE
Taxonomy Information Page

### ISSUE THREAD

**Issue by tigerhawkvok** [tigerhawkvok/asm-mammal-database#50]
Via @n8upham 
> Add a page called “Taxonomy” to the toolbar header— this page will contain sub-links and descriptions about the following:
>
>- List of new species (since MSW3) and their citations for “evidence" and “name”, including links to the article where we have that info
>- List of genus name transfers (since MSW3) and the citation for the change
>- Summary table comparing counts of species, genera, and families in MSW3 versus our MDD list

**Comment by tigerhawkvok** [comment]
Blocked on #54

**Comment by tigerhawkvok** [comment]
Just need final data for final testing to make sure this is ready to close.

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tigerhawkvok** [comment]
There is a list of straight-up new taxa (species authority year > `$updatesSinceAssessmentYear` ( = `2005`)):

![image](https://user-images.githubusercontent.com/165937/27258937-9441c30e-53bc-11e7-8678-a5255539cb38.png)


Migrations are computed from the intersection of:

- where the genus has an authority year newer than `$updatesSinceAssessmentYear` and the species older
- Where at least one entry in `deprecated_scientific` contains a declared taxon date newer than `$updatesSinceAssessmentYear`, eg, if `deprecated_scientific='{"Microtus montebelli":"Linneaus:1758$2016"}'` `2016` is new enough

parsing out as so:

![image](https://user-images.githubusercontent.com/165937/27258995-7e3a68da-53bd-11e7-8f89-54620b1a7a47.png)

**Comment by n8upham** [comment]
Okay, very cool, huge thanks for assembling this big update Philip.  Next time I’ll be sure to make it easier for you!

For this Taxonomy page— its not live yet, correct?

I like your strategy of having the database calculate these values on the fly and populate pages this way.  Its really awesome to have a real database underlying this website (another understatement!).

Appearance changes, based on what I see below:
- Can we have these pages be more data-rich on first sight?  E.g., have them in a table that can be sorted by year, genus, family, order, higher taxon?
- At some point, for each new species or genus transfer we’ll want the full citations in a standard format— plus display a link to the pdf of the article
- Really only 500 taxa changes since 2005?  I think our total was ~775 extant valid new species
- All “taxa changes” are newly recognized species, right?  If so change this to “newly recognized species”

Bigger issue:
- Do we have the official MSW3 taxonomy entered in the database as a “baseline” from which this new listing departs from?  Or else are the “new/ different” things calculated solely from authority year info?
- Having a static MSW3 baseline could be a good idea— I mention this because our current list is originally based on a IUCN download from April 2015, rather than MSW3 explicitly.  So quite possibly there are departures from MSW3 that we are not aware of yet.

Does this MSW3 baseline issue make sense?

Thanks
—nate
