### ISSUE TITLE
New Taxonomy Count

### ISSUE THREAD

**Issue by tigerhawkvok** [tigerhawkvok/asm-mammal-database#62]
@n8upham :

You mentioned in your email that the new list has 6301 new species. However, when I integrate and update the data, I get a new count of **6733**. 

It took a while to find the discrepancy, but I finally did. 

For example, let's look at the genus `Eospalax`. 

```
MariaDB [mammal2_asm_sadb]> select genus, species, internal_id from mammal_diversity_database where genus like 'eospalax' order by species;
+----------+-------------+-------------+
| genus    | species     | internal_id |
+----------+-------------+-------------+
| eospalax | baileyi     |   100000481 |
| eospalax | cansus      |   100000482 |
| eospalax | fontanierii |       14118 |
| eospalax | rothschildi |       14121 |
| eospalax | rufescens   |   100000483 |
| eospalax | smithii     |       14122 |
+----------+-------------+-------------+
6 rows in set (0.12 sec)
```

However, the base dataset you gave has this to say on the subject:

>split from frontanierii

for sp = `baileyi`, `cansus`, and `rufescens`. They are tagged as `splitFromExisting`, but also have no entry under `IfTransfer_oldSciName` (implying the old taxon is still valid, and it's just been differentiated). 

However, the dataset doesn't actually have `fontanierii` in it as a standalone taxon, making this ambiguous as to if it's been deprecated.

The size of this split from existing set seems to fully encompass the difference in counts.

For now, I'll operate under the assumption that both taxa are valid while I'm completing the data insertion/merge, but this ambiguity needs to be resolved!

**Comment by n8upham** [comment]
Hey Philip
Thanks for looking into this.  You’re correct that those 6 Eospalax are all valid in our Master list:

Eospalax_baileyi
Eospalax_cansus
Eospalax_fontanierii
Eospalax_rothschildi
Eospalax_rufescens
Eospalax_smithii

So that includes Eospalax_fontanierii for sure.  Split out (recognized as species-level variants) were Eospalax_baileyi, Eospalax_cansus, and Eospalax_rufescens.  But the parent taxon is still valid.

But how does this result in inflating the species number to 6733?  On the list I sent you (“MDD_taxonomy_fullList_cleanRelease_15June2017.txt”), there are 6360 species entries— of these, 54 are synonyms (juniorSynonym?=YES), resulting in 6306 valid taxa.  That is the number I sent in the email from the the other night.  Does that make sense?  There are a further 116 extinct species included in that 6306 number, so for “extant and valid” we are at 6190 species.

Are you saying that we need better agreement between the Master and the “newSinceMSW3” and “nameTransfer” lists that I sent?

Thanks
—n

**Comment by tigerhawkvok** [comment]
OK, I've found some of it ....

looks like some taxa didn't retain their unique ASM IDs (182 of them!)

eg,

```
MariaDB [mammal2_asm_sadb]> select genus, species, internal_id from mammal_diversity_database where species = 'yagouaroundi';
+-------------+--------------+-------------+
| genus       | species      | internal_id |
+-------------+--------------+-------------+
| herpailurus | yagouaroundi |        9948 |
| herpailurus | yagouaroundi |   400000178 |
+-------------+--------------+-------------+
2 rows in set (0.01 sec)
```

accounting for that I've got the total count down to 6554 with these known problem children

```
MariaDB [mammal2_asm_sadb]> select genus, species, count(*) as count from mammal_diversity_database group by species, genus having count > 1;
+--------------+-----------------+-------+
| genus        | species         | count |
+--------------+-----------------+-------+
| saimiri      | cassiquiarensis |     2 |
| dasypus      | kappleri        |     3 |
| spermophilus | pygmaeus        |     2 |
| spermophilus | relictus        |     2 |
+--------------+-----------------+-------+
4 rows in set (0.03 sec)
```

(the asm id column `internal_id` and the concatenated scientific name `canonical_sciname` are "unique" columns, so the problems so far have been collisions there ...)

**Comment by n8upham** [comment]
I’m still confused though— Where did the ID of 9948 come from for Herpailurus yagouaroundi?  The files I sent you contain the following lines for that taxon:

(MDD_taxonomy_fullList_cleanRelease_15June2017)
Placentalia	Boreoeutheria	CARNIVORA	FELIDAE	FELINAE	NA	Herpailurus	Herpailurus_yagouaroundi	NO	NA	moved_to_Herpailurus_from_Puma;_currently_recognized_as_a_monotypic_genus,_but_may_be_included_within_Puma	NA	0	400000178	0	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	1	Puma_yagouaroundi	_toLookUp	Kitchener,_A._C.,_Breitenmoser-Würsten,_C.,_Eizirik,_E.,_Gentry,_A.,_Werdelin,_L.,_Wilting,_A.,_&_Yamaguchi,_N._(2017)._A_revised_taxonomy_of_the_Felidae:_The_final_report_of_the_Cat_Classification_Task_Force_of_the_IUCN_Cat_Specialist_Group._Cat_News.

(nameTransfers_fullToMatch_15June2017_283species.txt)
Herpailurus_yagouaroundi	Puma_yagouaroundi	_toLookUp	FELIDAE	CARNIVORA	Kitchener,_A._C.,_Breitenmoser-Würsten,_C.,_Eizirik,_E.,_Gentry,_A.,_Werdelin,_L.,_Wilting,_A.,_&_Yamaguchi,_N._(2017)._A_revised_taxonomy_of_the_Felidae:_The_final_report_of_the_Cat_Classification_Task_Force_of_the_IUCN_Cat_Specialist_Group._Cat_News.

Is the 9948 a look-up from IUCN IDs?  Or was in a hold-over from the last database version?

Thanks
—n

**Comment by tigerhawkvok** [comment]
It's a hold over (the current version has a lot of extra data not contained in the file you sent that took a long time to generate, so I'm making sure the two are reconciled -- and while we ideally won't need to do this again (and just keep it updated via UI) it should prevent future issues)

**Comment by n8upham** [comment]
OK good point— I understand now.  Things like common names are of less concern right now given that they are highly subjective/variable for mammals.  If its easy to unify the next list with the previous IUCN-based data that is fine, but this is a secondary priority.  Many/most of the ~400 new species added since the 5911-species version will not be in IUCN anyway.

Yes agree that keeping things edited / updated via the UI will be preferable to keeping separate Excel files… (an understatement!)

—n
