### ISSUE TITLE
Downloading issues

### ISSUE THREAD

**Issue by bkohli** [tigerhawkvok/asm-mammal-database#73]
When attempting to download my search results I encountered two separate problems:

1. I tried several different searches of various sizes, but the HTML/PDF option nearly always failed (an exception is that the HTML option worked but not the pdf for Ursus arctos). A popup appears briefly which says "Failed to create file", but then the "Select Download Type" popup box remains up and I couldn't get it to disappear unless I refreshed the page.  

2. The CSV download option worked great, but I noticed one odd thing: If I clicked a search result to see the info on a particular species, selecting download from that species' page provides the option to "Use current search results", but turning that on didn't restrict the download.  The download worked, but I got the whole database.  Not a big problem, but having the option for the just the current search results made me think it was somehow able to tap into the search results that led me to the page I was on (of a single species) while downloading.  If this is unavoidable, perhaps a simple notification somewhere would help clarify?

**Comment by tigerhawkvok** [comment]
Hm -- the CSV should work restricted, and the HTML should always work.

The PDF having intermittent issues might be a "thing" (because the remote server has been inconsistent about its use of the binary it depends on).

Won't have a chance to take a deeper look at this until at least tomorrow though. Thanks for the report!

**Comment by bkohli** [comment]
Thanks! Just to clarify:  the restricted (current search results only) CSV download did work just fine for me when I was viewing the listed search results.  It was just when I clicked Download from a species page that it didn't seem to limit which records were downloaded.

**Comment by tigerhawkvok** [comment]
Ah! Yep, that was never considered as a case. Good call.

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tigerhawkvok** [comment]
1. Your base HTML / PDF download issue was caused by a very specific bad authority in the database that was causing the whole thing to fail. I've added a case to handle that issue @ 8ca91e2fa4cf31af779b233ef1694f672b71f770

2. I've added some cases ( d4429f1543c985128a5df46ef228c70603e27308 ) where if a failure mode is caught it'll re-enable the disabled buttons at the bottom. <kbd>ESC</kbd> always worked, but it's not obvious! 

3. I've played with server permissions a bit, but until I can get shell access on the shared server PDF generation will be basically at the server's whim

4. I'm going to see what I can do now about the generating a file just from the viewed taxon.
